# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedlist_forums', '0006_auto_20190605_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutions',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='status',
        ),
    ]
