# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedlist_forums', '0007_auto_20190605_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tips',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
