# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedlist_forums', '0009_auto_20190606_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='user',
        ),
        migrations.AddField(
            model_name='tips',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tips',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
